name: auto_bump_version

on:
  workflow_dispatch:
    inputs:
      bump_version: 
        type: choice
        description: Bumping version to
        options:
        - premajor
        - preminor
        - patch

jobs:
  auto_bump_version:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout main branch of repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1

    - name: Set environment variables
      shell: bash
      run: |
        echo "CURRENT_VERSION=$(poetry version --dry-run -s)" >> $GITHUB_ENV
        echo "BUMP_VERSION=$(poetry version ${{ github.event.inputs.bump_version }} --dry-run -s)" >> $GITHUB_ENV
        echo "RELEASE_VERSION=$(poetry version ${{ github.event.inputs.bump_version=='premajor' && 'major' || 'minor' }} --dry-run -s)" >> $GITHUB_ENV

    - name: Bump package version to ${{ github.event.inputs.bump_version }}
      shell: bash
      run: |
        poetry self add poetry-bumpversion
        poetry version ${{ github.event.inputs.bump_version }}

    - name: Commit and push to release branch
      if: ${{ github.event.inputs.bump_version != 'patch' }}
      run: |
        git config --global user.name "DevOps"
        git config --global user.email "DevOps@users.noreply.github.com"
        #git push -d origin "release/${{ env.RELEASE_VERSION }}"
        git checkout -b "release/${{ env.RELEASE_VERSION }}"
        git commit -am "Bumping version to ${{ github.event.inputs.bump_version }} (${{ env.CURRENT_VERSION }} to ${{ env.BUMP_VERSION }})"
        git push -u origin "release/${{ env.RELEASE_VERSION }}"

    - name: Commit and push to main branch (hotfix)
      if: ${{ github.event.inputs.bump_version == 'patch' }}
      run: |
        git config --global user.name "DevOps"
        git config --global user.email "DevOps@users.noreply.github.com"
        git commit -am "Bumping version to ${{ github.event.inputs.bump_version }} (${{ env.CURRENT_VERSION }} to ${{ env.BUMP_VERSION }})"
        git push

    - name: End
      shell: bash
      run: |
        echo "End"
      
